# Builds, tests, and pushes container images to GitHub Container Registry

name: 'Build images & deploy to AKS'

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Services/**'
      - 'src/Gateway/**'

env:
  REGISTRY: ghcr.io
  GATEWAY_TAG_PUSH: ghcr.io/iagonyii/gateway:latest
  SCAN_TAG_PUSH: ghcr.io/iagonyii/scanservice:latest
  USER_TAG_PUSH: ghcr.io/iagonyii/userservice:latest

jobs:

  build_push_images:

    runs-on: ubuntu-latest
    name: Build, scan, and push images
    
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build gateway
        uses: docker/build-push-action@v2
        with:
          context: src/Gateway
          push: false
          load: true
          tags: ${{ env.GATEWAY_TAG_PUSH }}
        
      - name: Scan gateway
        uses: anchore/scan-action@v3
        with:
          image: ${{ env.GATEWAY_TAG_PUSH }}
          
      - name: Push gateway
        uses: docker/build-push-action@v2
        with:
          context: src/Gateway
          push: true
          tags: ${{ env.GATEWAY_TAG_PUSH }}
          
      - name: Build scan
        uses: docker/build-push-action@v2
        with:
          context: src/Services/Scan
          push: false
          load: true
          tags: ${{ env.SCAN_TAG_PUSH }}
          
      - name: Scan scan
        uses: anchore/scan-action@v3
        with:
          image: ${{ env.SCAN_TAG_PUSH }}
          
      - name: Push scan
        uses: docker/build-push-action@v2
        with:
          context: src/Services/Scan
          push: true
          tags: ${{ env.SCAN_TAG_PUSH }}
          
      - name: Build user
        uses: docker/build-push-action@v2
        with:
          context: src/Services/User
          push: false
          load: true
          tags: ${{ env.USER_TAG_PUSH }}
          
      - name: Scan user
        uses: anchore/scan-action@v3
        with:
          image: ${{ env.USER_TAG_PUSH }}
          
      - name: Push user
        uses: docker/build-push-action@v2
        with:
          context: src/Services/User
          push: true
          tags: ${{ env.USER_TAG_PUSH }}

  deploy:
  
    needs: build_push_images
    runs-on: ubuntu-latest
    name: Deploy images to AKS
    
    steps:
      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: WebAppSafe
          resource-group: WebAppSafe
          
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          action: deploy
          manifests: |
            deploy/kubernetes-deployment.yaml
            deploy/pubsub.yaml
      
