# Builds, tests, and pushes container images to GitHub Container Registry

name: 'Build & push container images'

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Services/**'
      - 'src/Gateway/**'

env:
  REGISTRY: ghcr.io
  GATEWAY_TAG_PUSH: ghcr.io/iagonyii/gateway:latest
  SCAN_TAG_PUSH: ghcr.io/iagonyii/scanservice:latest
  USER_TAG_PUSH: ghcr.io/iagonyii/userservice:latest

jobs:

  gateway:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/Gateway
          push: true
          tags: ${{ env.GATEWAY_TAG_PUSH }}

  scanservice:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/Services/Scan
          push: true
          tags: ${{ env.SCAN_TAG_PUSH }}

  userservice:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/Services/User
          push: true
          tags: ${{ env.USER_TAG_PUSH }}
